language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest
install: npm ci
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: build
      if: type = push
      script: bash ./travis/build.sh
dist: trusty
sudo: true
