language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
before_install: sudo apt-get install md5sum
install: npm install --only=dev
jobs:
  include:
    - stage: test
      script: bash ./travis/test.sh
    - stage: build
      if: type = push
      script: bash ./travis/build.sh
    - stage: deploy
      if: type = push
      script: bash ./travis/pushback.sh
dist: trusty
sudo: true